package io.nawah.linux.core.provision

import com.google.common.truth.Truth.assertThat
import io.nawah.linux.core.model.DesktopSpec
import io.nawah.linux.core.model.Machine
import io.nawah.linux.core.model.MachinePermissions
import io.nawah.linux.core.model.MachineState
import io.nawah.linux.core.model.ResourceProfile
import io.nawah.linux.core.store.FileMachineStore
import org.junit.Before
import org.junit.Rule
import org.junit.Test
import org.junit.rules.TemporaryFolder
import java.io.File

/**
 * The app-owned files inside a machine must track the app, not the install.
 *
 * Written once at install time, a one-line fix to the session script could
 * only reach an existing machine by reinstalling the whole distribution —
 * twenty minutes and a gigabyte to deliver a corrected line of shell. These
 * tests are the guarantee that an app update is enough.
 */
class GuestFileWriterTest {

    @get:Rule val tmp = TemporaryFolder()

    private lateinit var store: FileMachineStore
    private lateinit var writer: GuestFileWriter

    private val xfce = DesktopSpec("xfce4", "XFCE 4", listOf("xfce4"), "startxfce4", 1)
    private val cli = DesktopSpec("none", "Command line only", emptyList(), "", 0)

    private val machine = Machine(
        id = "m1", name = "Linux", distroId = "debian-trixie", desktopId = "xfce4",
        profile = ResourceProfile.BALANCED, permissions = MachinePermissions(),
        displayWidth = 1280, displayHeight = 720,
        createdAtEpochMs = 0L, state = MachineState.READY,
    )

    @Before
    fun setUp() {
        store = FileMachineStore(tmp.newFolder("files"))
        writer = GuestFileWriter(store)
        store.rootfsDir(machine.id).mkdirs()
    }

    private fun guest(path: String) = File(store.rootfsDir(machine.id), path.trimStart('/'))

    @Test
    fun `the session script is written for the machine's desktop`() {
        writer.refresh(machine, xfce)

        assertThat(guest(GuestScripts.SESSION_PATH).readText()).contains("startxfce4")
    }

    @Test
    fun `the session script is executable`() {
        writer.refresh(machine, xfce)

        assertThat(guest(GuestScripts.SESSION_PATH).canExecute()).isTrue()
    }

    @Test
    fun `a stale session script from an older build is replaced`() {
        // Exactly the situation that forced two reinstalls: the machine holds a
        // script generated by a previous version of the app.
        guest(GuestScripts.SESSION_PATH).apply {
            parentFile?.mkdirs()
            writeText("#!/bin/bash\nNAWAH_START broken leftover\n")
        }

        writer.refresh(machine, xfce)

        val script = guest(GuestScripts.SESSION_PATH).readText()
        assertThat(script).doesNotContain("broken leftover")
        assertThat(script).contains("nawah: starting session")
    }

    @Test
    fun `the machine's own desktop is used, not a default`() {
        writer.refresh(machine.copy(desktopId = "none"), cli)

        assertThat(guest(GuestScripts.SESSION_PATH).readText()).contains("xterm")
    }

    @Test
    fun `a desktop missing from the catalog still produces a usable session`() {
        // A machine installed by an older build whose desktop id was retired
        // must still start rather than fail to launch at all.
        writer.refresh(machine, null)

        val script = guest(GuestScripts.SESSION_PATH).readText()
        assertThat(script).contains("xterm")
        assertThat(script).contains("nawah: starting session")
    }

    @Test
    fun `audio permission is reflected on every refresh, not frozen at install`() {
        writer.refresh(machine, xfce)
        assertThat(guest(GuestScripts.SESSION_PATH).readText()).contains("PULSE_SERVER")

        writer.refresh(machine.copy(permissions = MachinePermissions(audioOut = false)), xfce)
        assertThat(guest(GuestScripts.SESSION_PATH).readText()).doesNotContain("PULSE_SERVER")
    }

    @Test
    fun `the resource profile is reflected on every refresh`() {
        writer.refresh(machine.copy(profile = ResourceProfile.FULL), xfce)
        assertThat(guest(GuestScripts.SESSION_PATH).readText()).doesNotContain("use_compositing")

        writer.refresh(machine.copy(profile = ResourceProfile.LIGHT), xfce)
        assertThat(guest(GuestScripts.SESSION_PATH).readText()).contains("use_compositing")
    }

    @Test
    fun `refreshing repeatedly is stable`() {
        writer.refresh(machine, xfce)
        val script = guest(GuestScripts.SESSION_PATH).readText()

        repeat(3) { writer.refresh(machine, xfce) }

        assertThat(guest(GuestScripts.SESSION_PATH).readText()).isEqualTo(script)
    }
}
