package io.nawah.linux.core.provision

import io.nawah.linux.core.model.DesktopSpec
import io.nawah.linux.core.model.ResourceProfile

/**
 * The one script that lives inside the guest filesystem.
 *
 * There used to be two, plus a `loader.apk`: the guest was expected to launch
 * the X server itself through `app_process`. It never worked — running an
 * Android runtime under proot's ptrace exits immediately with status 0 — and
 * the whole mechanism is gone. The X server is started on the Android side by
 * `X11Bridge`; all the guest does is wait for its socket and start a desktop.
 */
object GuestScripts {

    const val SESSION_PATH = "/usr/local/bin/nawah-session"

    /** Where the Android-side X server binds. Inside the guest this is `/tmp`. */
    const val X_SOCKET = "/tmp/.X11-unix/X0"

    /** Private, 0700. `/tmp` is 1777 and dbus will not use it. */
    const val RUNTIME_DIR = "/run/user/0"

    /** The USB helper, written fresh on every launch. */
    const val USB_HELPER_PATH = "/usr/local/bin/nawah-usb"

    /** Where the app listens for what a pty cannot carry. */
    const val USB_CONTROL_PORT = 4721

    /** The serial port as the container sees it. */
    const val USB_TTY = "/dev/ttyUSB0"

    /**
     * The guest side of the USB control channel.
     *
     * Pure bash over `/dev/tcp`, so a machine needs no extra package to reset a
     * board. It exists because a pseudo-terminal carries no modem control
     * lines: `drivers/tty/pty.c` defines no `.tiocmset` for Unix98 ptys, so
     * `TIOCMSET` returns `-ENOTTY` and every tool that toggles DTR to reset a
     * board gets an error instead of a reset. That is the kernel's behaviour,
     * not something this app can fix from inside the container — so the reset
     * is asked for out of band, and the app performs it on the real device.
     */
    fun usbHelper(): String = buildString {
        val d = "$"
        appendLine("#!/bin/bash")
        appendLine("# Generated by Nawah on every launch. Do not edit.")
        appendLine("set -u")
        appendLine()
        appendLine("PORT=$USB_CONTROL_PORT")
        appendLine()
        appendLine("usage() {")
        appendLine("  cat >&2 <<'USAGE'")
        appendLine("nawah-usb - control the USB serial line that Nawah bridges in.")
        appendLine()
        appendLine("  nawah-usb status         what the app has the line set to")
        appendLine("  nawah-usb dtr on|off     drive DTR")
        appendLine("  nawah-usb rts on|off     drive RTS")
        appendLine("  nawah-usb reset          pulse DTR: resets an Arduino")
        appendLine("  nawah-usb reset-esp      BOOT + reset: ESP32 download mode")
        appendLine()
        appendLine("Why this exists: $USB_TTY is a pseudo-terminal, and Linux ptys")
        appendLine("carry no modem control lines. avrdude and esptool cannot toggle DTR")
        appendLine("through it, so ask here first and pass their own no-reset flags.")
        appendLine("USAGE")
        appendLine("  exit 2")
        appendLine("}")
        appendLine()
        appendLine("[ ${d}# -ge 1 ] || usage")
        appendLine("case \"${d}1\" in -h|--help|help) usage ;; esac")
        appendLine()
        appendLine("exec 3<>/dev/tcp/127.0.0.1/${d}PORT 2>/dev/null || {")
        appendLine("  echo \"nawah-usb: nothing is listening on 127.0.0.1:${d}PORT.\" >&2")
        appendLine("  echo \"nawah-usb: no USB device is attached to this system.\" >&2")
        appendLine("  exit 1")
        appendLine("}")
        appendLine("printf '%s\\n' \"${d}*\" >&3")
        appendLine("read -r reply <&3")
        appendLine("exec 3<&-")
        appendLine("echo \"${d}reply\"")
        appendLine("case \"${d}reply\" in ok*) exit 0 ;; *) exit 1 ;; esac")
    }

    /** PulseAudio configuration, written fresh on every launch. */
    const val PULSE_CONFIG_PATH = "/etc/pulse/nawah.pa"

    /** Where the Android side reads what the system plays. */
    const val AUDIO_OUT_PORT = 4713

    /** Where the Android side writes what the microphone hears. */
    const val AUDIO_IN_PORT = 4714

    /** One format for both directions, chosen to need no conversion anywhere. */
    const val AUDIO_RATE = 48_000
    const val AUDIO_FORMAT = "s16le"

    /**
     * The PulseAudio configuration the guest's audio server is started with.
     *
     * There is no sound card inside a proot container and there never will be:
     * ALSA has nothing to open, and Android's audio output is reachable only
     * from the Android side. So the guest gets a *null sink* — a device that
     * accepts audio and discards it — and its monitor is served over loopback
     * TCP as raw PCM. The app connects, reads those bytes and hands them to an
     * `AudioTrack`. Loopback works with no bind and no forwarding because proot
     * creates no network namespace: the container and the app share one stack.
     *
     * The microphone is the same idea backwards. A second null sink stands in
     * for a capture device, the app writes recorded PCM into it, and the guest
     * records from its monitor.
     *
     * `.nofail` is deliberate: a microphone module that fails to load must not
     * take the speaker down with it.
     */
    fun pulseConfig(microphone: Boolean): String = buildString {
        appendLine("# Generated by Nawah on every launch. Do not edit.")
        appendLine(".nofail")
        appendLine()
        appendLine("load-module module-null-sink sink_name=$SINK_OUT " +
            "rate=$AUDIO_RATE channels=2 " +
            "sink_properties=device.description=Nawah_speaker")
        appendLine("set-default-sink $SINK_OUT")
        appendLine("load-module module-simple-protocol-tcp record=true " +
            "source=$SINK_OUT.monitor listen=127.0.0.1 port=$AUDIO_OUT_PORT " +
            "format=$AUDIO_FORMAT rate=$AUDIO_RATE channels=2")
        if (microphone) {
            appendLine()
            appendLine("load-module module-null-sink sink_name=$SINK_MIC " +
                "rate=$AUDIO_RATE channels=1 " +
                "sink_properties=device.description=Nawah_microphone")
            appendLine("set-default-source $SINK_MIC.monitor")
            appendLine("load-module module-simple-protocol-tcp playback=true " +
                "sink=$SINK_MIC listen=127.0.0.1 port=$AUDIO_IN_PORT " +
                "format=$AUDIO_FORMAT rate=$AUDIO_RATE channels=1")
        }
    }

    private const val SINK_OUT = "nawah_out"
    private const val SINK_MIC = "nawah_mic"

    /**
     * Starts the desktop.
     *
     * It waits for a display that *answers*, not for a socket file to exist.
     * The distinction is the whole point: a killed server leaves its socket
     * behind, and connecting to that file fails with ECONNREFUSED while the
     * file is plainly there.
     */
    fun session(desktop: DesktopSpec, profile: ResourceProfile, audio: Boolean): String {
        // "Command line only" still needs a client, or X comes up with nothing
        // drawn on it and the user is looking at a black rectangle wondering
        // what broke. xterm is in the base package set for exactly this.
        val start = desktop.startCommand.ifBlank { "xterm -fa Monospace -fs 14" }
        val lightweight = profile != ResourceProfile.FULL
        return buildString {
            appendLine("#!/bin/bash")
            appendLine("# Generated by Nawah on every launch. Everything it prints is")
            appendLine("# captured into the machine's session log and shown in the app.")
            appendLine("set -u")
            appendLine()
            appendLine("echo \"nawah: starting session at \$(date -u '+%H:%M:%S')\"")
            appendLine()
            appendLine("# Timed, because \"it is slow to start\" needs an answer and not a")
            appendLine("# guess. EPOCHREALTIME is a bash builtin, so reading it costs no")
            appendLine("# process -- which matters when every process here is ptraced.")
            appendLine("nawah_t0=\${EPOCHREALTIME:-0}")
            appendLine("nawah_since() {")
            appendLine("  [ \"\$nawah_t0\" = 0 ] && return 0")
            appendLine("  awk -v a=\"\$nawah_t0\" -v b=\"\${EPOCHREALTIME:-0}\" \\")
            appendLine("    'BEGIN { printf \"%.2f\", b - a }' 2>/dev/null")
            appendLine("}")
            appendLine()
            appendLine("export DISPLAY=:0")
            appendLine("export XDG_SESSION_TYPE=x11")
            appendLine("export LANG=${'$'}{LANG:-C.UTF-8}")
            appendLine()
            appendLine("# dbus refuses a world-writable XDG_RUNTIME_DIR and then fails to")
            appendLine("# create its own socket:")
            appendLine("#   Unable to set up transient service directory:")
            appendLine("#   XDG_RUNTIME_DIR \"/tmp\" can be written by others (mode 041777)")
            appendLine("# So it gets a private one of its own, 0700, as the spec requires.")
            appendLine("export XDG_RUNTIME_DIR=$RUNTIME_DIR")
            appendLine("mkdir -p -m 700 \"\$XDG_RUNTIME_DIR\" 2>/dev/null || true")
            appendLine("chmod 700 \"\$XDG_RUNTIME_DIR\" 2>/dev/null || true")
            appendLine()
            appendLine("# The X server is NOT started here. It runs on the Android side")
            appendLine("# and binds its socket in <rootfs>/tmp, which is this container's")
            appendLine("# own /tmp -- so it simply appears below, with no bind involved.")
            appendLine("# Starting an Android runtime under proot's ptrace was the mistake")
            appendLine("# that made this exit instantly with status 0 and no desktop.")
            appendLine("#")
            appendLine("# What is waited for is a display that ANSWERS, not a file that")
            appendLine("# exists. A killed server leaves its socket behind, and connecting")
            appendLine("# to that file fails with ECONNREFUSED while the file is plainly")
            appendLine("# there -- which is why this used to work once and then never again.")
            appendLine("display_ready() {")
            appendLine("  # The cheap test first. Every process started in here is")
            appendLine("  # started under proot's ptrace, which costs far more than a")
            appendLine("  # stat -- and polling xset four times a second was paying")
            appendLine("  # that price against the very startup it was waiting for.")
            appendLine("  [ -e $X_SOCKET ] || return 1")
            appendLine("  if command -v xset >/dev/null 2>&1; then")
            appendLine("    xset -q >/dev/null 2>&1")
            appendLine("  else")
            appendLine("    return 0")
            appendLine("  fi")
            appendLine("}")
            appendLine("for i in ${'$'}(seq 1 160); do")
            appendLine("  display_ready && break")
            appendLine("  sleep 0.25")
            appendLine("done")
            appendLine("if ! display_ready; then")
            appendLine("  if [ -e $X_SOCKET ]; then")
            appendLine("    echo \"nawah: $X_SOCKET exists but the display refuses connections.\"")
            appendLine("    echo \"nawah: that is a socket left by an earlier session, not a server.\"")
            appendLine("  else")
            appendLine("    echo \"nawah: no X display on :0 after 40s.\"")
            appendLine("  fi")
            appendLine("  echo \"nawah: the Android-side display server did not come up;\"")
            appendLine("  echo \"nawah: its own output is above this line in the log.\"")
            appendLine("  exit 1")
            appendLine("fi")
            appendLine("echo \"nawah: the display is answering on :0 — \$(nawah_since)s into the session\"")
            appendLine()
            if (audio) {
                appendLine("# Sound. The server runs HERE, inside the system, because this is")
                appendLine("# where the applications are; it plays into a null sink whose")
                appendLine("# monitor the app reads over loopback. PULSE_SERVER is deliberately")
                appendLine("# NOT set: it used to name a TCP port nothing ever listened on,")
                appendLine("# which is why the sound switch never did anything.")
                appendLine("if command -v pulseaudio >/dev/null 2>&1; then")
                appendLine("  if pactl info >/dev/null 2>&1; then")
                appendLine("    echo \"nawah: audio server already running\"")
                appendLine("  else")
                appendLine("    pulseaudio --daemonize=no --exit-idle-time=-1 --disable-shm=1 \\")
                appendLine("      -n -F $PULSE_CONFIG_PATH --log-target=stderr \\")
                appendLine("      >/tmp/nawah-pulse.log 2>&1 &")
                appendLine("    for i in \$(seq 1 20); do")
                appendLine("      pactl info >/dev/null 2>&1 && break")
                appendLine("      sleep 0.25")
                appendLine("    done")
                appendLine("    if pactl info >/dev/null 2>&1; then")
                appendLine("      echo \"nawah: audio server started\"")
                appendLine("    else")
                appendLine("      echo \"nawah: the audio server did not start; see /tmp/nawah-pulse.log\"")
                appendLine("    fi")
                appendLine("  fi")
                appendLine("else")
                appendLine("  echo \"nawah: pulseaudio is not installed; the desktop will be silent\"")
                appendLine("fi")
                appendLine()
            }
            appendLine("command -v dbus-launch >/dev/null || {")
            appendLine("  echo \"nawah: dbus-launch is missing; install dbus-x11\"")
            appendLine("  exit 1")
            appendLine("}")
            appendLine("command -v ${start.substringBefore(' ')} >/dev/null || {")
            appendLine("  echo \"nawah: ${start.substringBefore(' ')} is not installed in this system\"")
            appendLine("  exit 1")
            appendLine("}")
            appendLine()
            appendLine("# The root window's cursor, which is otherwise the bare X that")
            appendLine("# X11 has shipped since 1985. The glyph comes from the core cursor")
            appendLine("# font in xfonts-base, so this costs no package and no theme.")
            appendLine("command -v xsetroot >/dev/null 2>&1 && xsetroot -cursor_name left_ptr")
            appendLine()
            if (lightweight) {
                appendLine("# Compositing off, written as configuration rather than asked for")
                appendLine("# at run time: xfconf-query needs its daemon, which is not up yet")
                appendLine("# when this runs, so the old call quietly did nothing. There is no")
                appendLine("# GPU here -- every shadow and fade is drawn by the CPU -- and the")
                appendLine("# window manager is the thing that pays for it.")
                appendLine("xfwm_conf=\"\$HOME/.config/xfce4/xfconf/xfce-perchannel-xml\"")
                appendLine("if [ ! -e \"\$xfwm_conf/xfwm4.xml\" ]; then")
                appendLine("  mkdir -p \"\$xfwm_conf\"")
                appendLine("  cat > \"\$xfwm_conf/xfwm4.xml\" <<'XFWM'")
                appendLine("<?xml version=\"1.0\" encoding=\"UTF-8\"?>")
                appendLine("<channel name=\"xfwm4\" version=\"1.0\">")
                appendLine("  <property name=\"general\" type=\"empty\">")
                appendLine("    <property name=\"use_compositing\" type=\"bool\" value=\"false\"/>")
                appendLine("    <property name=\"box_move\" type=\"bool\" value=\"true\"/>")
                appendLine("    <property name=\"box_resize\" type=\"bool\" value=\"true\"/>")
                appendLine("  </property>")
                appendLine("</channel>")
                appendLine("XFWM")
                appendLine("fi")
                appendLine()
            }
            appendLine("echo \"nawah: launching $start — \$(nawah_since)s into the session\"")
            appendLine("dbus-launch --exit-with-session $start")
            appendLine("status=\$?")
            appendLine("echo \"nawah: session ended with status \$status\"")
            appendLine("exit \$status")
        }
    }

}
