package io.nawah.linux.core.provision

import io.nawah.linux.core.model.DesktopSpec
import io.nawah.linux.core.model.ResourceProfile

/**
 * The two scripts that live inside the guest filesystem.
 *
 * They are generated rather than shipped because both embed this build's
 * application id, and one of them is the load-bearing half of the X11 bridge.
 */
object GuestScripts {

    const val LOADER_PATH = "/usr/libexec/nawah-x11/loader.apk"
    const val BRIDGE_PATH = "/usr/bin/nawah-x11"
    const val SESSION_PATH = "/usr/local/bin/nawah-session"

    /**
     * Hands the X connection to the Android side.
     *
     * `app_process` is Android's own Java launcher. Running it from inside the
     * container works only because proot binds `/system`, `/apex` and
     * `/linkerconfig` -- if the desktop never appears, that is the first thing
     * to check. The loader it starts verifies the host app's signing
     * certificate before loading any of our code, which is also why a rebuild
     * with a different key needs "Repair X11 bridge".
     */
    fun bridge(applicationId: String): String = """
        #!/bin/sh
        if [ ! -e /system/bin/app_process ]; then
          echo "nawah-x11: /system/bin/app_process is not visible inside this container." >&2
          echo "nawah-x11: the session was started without the Android system bind mounts." >&2
          exit 1
        fi
        [ -z "${'$'}{LD_LIBRARY_PATH+x}" ] || export XSTARTUP_LD_LIBRARY_PATH="${'$'}LD_LIBRARY_PATH"
        [ -z "${'$'}{LD_PRELOAD+x}" ] || export XSTARTUP_LD_PRELOAD="${'$'}LD_PRELOAD"
        [ -z "${'$'}{CLASSPATH+x}" ] || export XSTARTUP_CLASSPATH="${'$'}CLASSPATH"
        export CLASSPATH=$LOADER_PATH
        unset LD_LIBRARY_PATH LD_PRELOAD
        exec /system/bin/app_process -Xnoimage-dex2oat / \
          --nice-name="nawah-x11 $applicationId ${'$'}*" com.termux.x11.Loader "${'$'}@"
    """.trimIndent() + "\n"

    /**
     * Starts the desktop.
     *
     * The X server and this script race deliberately: `CmdEntryPoint`
     * re-broadcasts its Binder once a second until the activity answers, so
     * neither side has to wait for the other.
     */
    fun session(desktop: DesktopSpec, profile: ResourceProfile, audio: Boolean): String {
        // "Command line only" still needs a client, or X comes up with nothing
        // drawn on it and the user is looking at a black rectangle wondering
        // what broke. xterm is in the base package set for exactly this.
        val start = desktop.startCommand.ifBlank { "xterm -fa Monospace -fs 14" }
        val lightweight = profile != ResourceProfile.FULL
        return buildString {
            appendLine("#!/bin/bash")
            appendLine("# Generated by Nawah. Everything it prints is captured into")
            appendLine("# the machine's session log and shown in the app.")
            appendLine("set -u")
            appendLine()
            appendLine("echo \"nawah: starting session at \$(date -u '+%H:%M:%S')\"")
            appendLine()
            appendLine("# Preflight. Each of these has failed on a real device, and each")
            appendLine("# produced the same useless symptom: a black screen.")
            appendLine("fail=0")
            appendLine("[ -x $BRIDGE_PATH ] || { echo \"nawah: MISSING $BRIDGE_PATH\"; fail=1; }")
            appendLine("[ -r $LOADER_PATH ] || { echo \"nawah: MISSING $LOADER_PATH\"; fail=1; }")
            appendLine("[ -x /system/bin/app_process ] || {")
            appendLine("  echo \"nawah: /system/bin/app_process is not visible in this container.\"")
            appendLine("  echo \"nawah: the Android system bind mounts are missing.\"")
            appendLine("  fail=1")
            appendLine("}")
            appendLine("command -v dbus-launch >/dev/null || echo \"nawah: dbus-launch not found\"")
            appendLine("command -v ${'$'}{NAWAH_START%% *} >/dev/null 2>&1 || true")
            appendLine("[ \"\$fail\" = 0 ] || { echo \"nawah: preflight failed, not starting X\"; exit 1; }")
            appendLine()
            appendLine("export DISPLAY=:0")
            appendLine("export XDG_RUNTIME_DIR=/tmp")
            appendLine("export XDG_SESSION_TYPE=x11")
            appendLine("export LANG=\${LANG:-C.UTF-8}")
            if (audio) appendLine("export PULSE_SERVER=\${PULSE_SERVER:-tcp:127.0.0.1:4713}")
            appendLine()
            appendLine("mkdir -p /tmp/.X11-unix && chmod 1777 /tmp /tmp/.X11-unix")
            appendLine()
            appendLine("echo \"nawah: starting the display bridge\"")
            appendLine("$BRIDGE_PATH :0 &")
            appendLine("bridge_pid=\$!")
            appendLine()
            appendLine("# Wait for the X socket the Android-side server binds under TMPDIR.")
            appendLine("for i in \$(seq 1 60); do")
            appendLine("  [ -e /tmp/.X11-unix/X0 ] && break")
            appendLine("  kill -0 \$bridge_pid 2>/dev/null || {")
            appendLine("    echo \"nawah: the display bridge exited before X came up\"")
            appendLine("    wait \$bridge_pid")
            appendLine("    echo \"nawah: bridge exit status \$?\"")
            appendLine("    exit 1")
            appendLine("  }")
            appendLine("  sleep 0.25")
            appendLine("done")
            appendLine()
            appendLine("if [ ! -e /tmp/.X11-unix/X0 ]; then")
            appendLine("  echo \"nawah: X socket never appeared at /tmp/.X11-unix/X0 after 15s\"")
            appendLine("  echo \"nawah: the app side of the bridge did not answer.\"")
            appendLine("  exit 1")
            appendLine("fi")
            appendLine("echo \"nawah: X is up\"")
            appendLine()
            if (lightweight) {
                appendLine("# Resource profile: compositing off. proot cannot cap memory --")
                appendLine("# there are no cgroups without root -- so the profile changes what")
                appendLine("# actually runs instead of pretending to enforce a limit.")
                appendLine("xfconf-query -c xfwm4 -p /general/use_compositing -s false 2>/dev/null || true")
                appendLine()
            }
            appendLine("echo \"nawah: launching $start\"")
            appendLine("dbus-launch --exit-with-session $start")
            appendLine("status=\$?")
            appendLine("echo \"nawah: session ended with status \$status\"")
            appendLine("exit \$status")
        }
    }

}
