package io.nawah.linux.core.provision

import io.nawah.linux.core.model.DesktopSpec
import io.nawah.linux.core.model.ResourceProfile

/**
 * The one script that lives inside the guest filesystem.
 *
 * There used to be two, plus a `loader.apk`: the guest was expected to launch
 * the X server itself through `app_process`. It never worked — running an
 * Android runtime under proot's ptrace exits immediately with status 0 — and
 * the whole mechanism is gone. The X server is started on the Android side by
 * `X11Bridge`; all the guest does is wait for its socket and start a desktop.
 */
object GuestScripts {

    const val SESSION_PATH = "/usr/local/bin/nawah-session"

    /**
     * Starts the desktop.
     *
     * It waits for the X socket rather than racing it: the server is started
     * first, but it is a whole X server and it does not come up instantly.
     */
    fun session(desktop: DesktopSpec, profile: ResourceProfile, audio: Boolean): String {
        // "Command line only" still needs a client, or X comes up with nothing
        // drawn on it and the user is looking at a black rectangle wondering
        // what broke. xterm is in the base package set for exactly this.
        val start = desktop.startCommand.ifBlank { "xterm -fa Monospace -fs 14" }
        val lightweight = profile != ResourceProfile.FULL
        return buildString {
            appendLine("#!/bin/bash")
            appendLine("# Generated by Nawah on every launch. Everything it prints is")
            appendLine("# captured into the machine's session log and shown in the app.")
            appendLine("set -u")
            appendLine()
            appendLine("echo \"nawah: starting session at \$(date -u '+%H:%M:%S')\"")
            appendLine()
            appendLine("# The X server is NOT started here. It runs on the Android side")
            appendLine("# and binds its socket in <rootfs>/tmp, which is this container's")
            appendLine("# own /tmp -- so it simply appears below, with no bind involved.")
            appendLine("# Starting an Android runtime under proot's ptrace was the mistake")
            appendLine("# that made this exit instantly with status 0 and no desktop.")
            appendLine("for i in \$(seq 1 80); do")
            appendLine("  [ -e /tmp/.X11-unix/X0 ] && break")
            appendLine("  sleep 0.25")
            appendLine("done")
            appendLine("if [ ! -e /tmp/.X11-unix/X0 ]; then")
            appendLine("  echo \"nawah: no X socket at /tmp/.X11-unix/X0 after 20s.\"")
            appendLine("  echo \"nawah: the Android-side display server did not come up;\"")
            appendLine("  echo \"nawah: its own output is above this line in the log.\"")
            appendLine("  exit 1")
            appendLine("fi")
            appendLine("echo \"nawah: found the X socket\"")
            appendLine()
            appendLine("export DISPLAY=:0")
            appendLine("export XDG_RUNTIME_DIR=/tmp")
            appendLine("export XDG_SESSION_TYPE=x11")
            appendLine("export LANG=\${LANG:-C.UTF-8}")
            if (audio) appendLine("export PULSE_SERVER=\${PULSE_SERVER:-tcp:127.0.0.1:4713}")
            appendLine()
            appendLine("command -v dbus-launch >/dev/null || {")
            appendLine("  echo \"nawah: dbus-launch is missing; install dbus-x11\"")
            appendLine("  exit 1")
            appendLine("}")
            appendLine("command -v ${start.substringBefore(' ')} >/dev/null || {")
            appendLine("  echo \"nawah: ${start.substringBefore(' ')} is not installed in this system\"")
            appendLine("  exit 1")
            appendLine("}")
            appendLine()
            if (lightweight) {
                appendLine("# Resource profile: compositing off. proot cannot cap memory --")
                appendLine("# there are no cgroups without root -- so the profile changes what")
                appendLine("# actually runs instead of pretending to enforce a limit.")
                appendLine("xfconf-query -c xfwm4 -p /general/use_compositing -s false 2>/dev/null || true")
                appendLine()
            }
            appendLine("echo \"nawah: launching $start\"")
            appendLine("dbus-launch --exit-with-session $start")
            appendLine("status=\$?")
            appendLine("echo \"nawah: session ended with status \$status\"")
            appendLine("exit \$status")
        }
    }

}
